FIELD_ALIASES = {
    "headline": "headline",
    "address": "address",
    "price": "price",
    "description": "description",
    "category": "Category",
    "date_available": "Date Available",
    "date_posted": "Date Posted",
    "shared": "Shared",
    "sublet": "Sublet",
    "beds": "Beds",
    "listing_id": "listing_id",
    "parking": "Parking",
    "no_smoking": "No Smoking",
    "laundry_facilities": "Laundry Facilities",
    "cooking_facilities": "Cooking Facilities",
    "photos": "Photos",
    "check_sum_description": "Check Sum Description",
    "check_sum_json": "Check Sum JSON",
}
